export const userData = [
    {name: 'De Diademond', newChat: true, time: "24s"},
    {name: 'AnthoLeBg', newChat: false, time: "24min"},
    {name: 'Toto tata', newChat: true, time: "44min"},
    {name: 'Johanna Unison', newChat: true, time: "54min"},
    {name: 'John Doe', newChat: false, time: "1h"},
    {name: 'De Diamqond', newChat: true, time: "2h"},
    {name: 'De Diamfond', newChat: true, time: "24s"},
    {name: 'AnthsoLeBg', newChat: false, time: "24min"},
    {name: 'Totedo tata', newChat: false, time: "44min"},
    {name: 'Johannrfa Unison', newChat: true, time: "54min"},
    {name: 'Johtrgtn Doe', newChat: false, time: "1h"},
    {name: 'De gttgDiamond', newChat: false, time: "2h"},
    {name: 'De Dgrrtiamond', newChat: true, time: "24s"},
    {name: 'AnthogtgLeBg', newChat: false, time: "24min"},
    {name: 'Totgtgo tata', newChat: true, time: "44min"},
    {name: 'Johanndeea Unison', newChat: true, time: "54min"},
    {name: 'John Dqsoe', newChat: false, time: "1h"},
    {name: 'De Diamsfyhyyond', newChat: true, time: "2h"},
]
